/**Get All Players */
export const getAllPlayers = () => {
	return [
		{
			defenders: [
				{
					goalkeepers: [
						{
							name: "Allan Allano",
							age: 31,
							position: "Goalkeeper",
							id: 1,
							strengths: "Sweeping, Long Passes, Cross-Claiming",
							personality: "Courageous",
							alias: "Allano",
							height: "179cm",
							strongFoot: "Right",
							emoji: "🤖",
							joined: "2018",
							games: 25,
							goals: 1,
							assists: 0,
							favouriteMove: "The Drop Kick",
							playerTake:
								"Dabonii is family. Here you feel right at home and the togetherness elevates you to a different level.",
						},
						{
							name: "Collins Collo",
							age: 17,
							position: "Goalkeeper",
							id: 2,
							strengths: "Cross-Claiming, Sweeper",
							personality: "Courageous",
							alias: "Collo",
							height: "175cm",
							strongFoot: "Right",
							emoji: "🤨",
							joined: "2024",
							games: 10,
							goals: 0,
							assists: 0,
							favouriteMove: "The Sweeper Keeper",
							playerTake:
								"Dabonii is family. Here you feel right at home and the togetherness elevates you to a different level.",
						},
						{
							name: "Jagoal",
							age: 23,
							position: "Goalkeeper",
							id: 3,
							strengths: "Shot-Stopper",
							personality: "Humble",
							alias: "Jagoal",
							height: "176cm",
							strongFoot: "Right",
							emoji: "🙂",
							joined: "2023",
							games: 18,
							goals: 6,
							assists: 3,
							favouriteMove: "The Curling Cross",
							playerTake:
								"Dabonii is family. Here you feel right at home and the togetherness elevates you to a different level.",
						},
					],
				},
				{
					centerBacks: [
						{
							name: "Samuel Njoroge",
							age: 37,
							position: "CB",
							id: 1,
							strengths: "Stamina, Positioning",
							personality: "Competent",
						},
						{
							name: "Elijah Owino",
							age: 29,
							position: "CB",
							id: 2,
							strengths: "Passing, First-Touch",
							personality: "Brave",
						},
						{
							name: "Eutychus",
							age: 20,
							position: "CB",
							id: 3,
							strengths: "Stamina, Pace",
							personality: "Competent",
						},
						{
							name: "Alex Mwangi",
							age: 34,
							position: "CB",
							id: 4,
							strengths: "Tackling,Strength",
							personality: "Brave",
						},
						{
							name: "Joseph Ngina",
							age: 39,
							position: "CB",
							id: 5,
							strengths: "Hard-Tackler, Passing",
							personality: "Honest",
						},
						{
							name: "Lwanga Viketi",
							age: 43,
							position: "CB",
							id: 6,
							strengths: "Tackling, Stamina",
							personality: "Competent",
						},
						{
							name: "Robert Sifuma",
							age: 40,
							position: "CB",
							id: 7,
							strengths: "Shooting,",
							personality: "Joker",
						},
						{
							name: "Idris",
							age: 31,
							position: "CB",
							id: 8,
							strengths: "Stamina, Pace, Power",
							personality: "Competent",
						},
					],
				},
				{
					fullbacks: [
						{
							name: "Joshua Junior",
							age: "28",
							position: "RB",
							id: 1,
							strengths: "Stamina, Pace",
							personality: "Competent",
						},
						{
							name: "Omanyala Oma",
							age: "23",
							position: "RB",
							id: 2,
							strengths: "Tackling, Speed",
							personality: "Brave",
						},
						{
							name: "Eshbon Moha",
							age: "35",
							position: "LB",
							id: 3,
							strengths: "Touch, Short Passes",
							personality: "Outgoing",
						},
						{
							name: "Martin Mbaya",
							age: "38",
							position: "RB",
							id: 4,
							strengths: "Dribbling, Long Passes",
							personality: "Humble",
						},
						{
							name: "Dan Lumiti",
							age: "31",
							position: "RB",
							id: 5,
							strengths: "Stamina, Pace",
							personality: "Brave",
						},
						{
							name: "Chris Jadolo",
							age: "40",
							position: "RB",
							id: 6,
							strengths: "Positioning, Man-marking",
							personality: "Compassionate",
						},
						{
							name: "Clinton Bukele",
							age: "26",
							position: "LB",
							id: 7,
							strengths: "Tackling, Passing",
							personality: "Competent",
						},
						{
							name: "Mugesto",
							age: "25",
							position: "RB",
							id: 8,
							strengths: "Passing, Vision",
							personality: "Brave",
						},
						{
							name: "Kasee",
							age: "36",
							position: "RB",
							id: 9,
							strengths: "Stamina, Pace",
							personality: "Competent",
						},
						{
							name: "Rutto",
							age: "42",
							position: "RB",
							id: 10,
							strengths: "Workaholic, Tenacious, Tackling",
							personality: "Brave",
						},
						{
							name: "Tyso",
							age: "27",
							position: "RB",
							id: 11,
							strengths: "Relentless, Tenacious, Workaholic",
							personality: "No-nonsense",
						},
						{
							name: "Cornelius Muli",
							age: "23",
							position: "LB",
							id: 12,
							strengths: "Shooting, Dribbling, Crossing",
							personality: "Friendly",
							alias: "Muli",
							height: "177cm",
							strongFoot: "Left",
							emoji: "😄",
							joined: "2021",
							games: 18,
							goals: 6,
							assists: 3,
							favouriteMove: "The Curling Cross",
							playerTake:
								"Dabonii is family. Here you feel right at home and the togetherness elevates you to a different level.",
						},
					],
				},
			],
		},
		{
			midfielders: [
				{
					AttackingMidfielders: [
						{
							name: "Kennedy Atendo",
							age: "31",
							position: "Attacking Midfielder",
							id: 1,
							strengths: "speed, shooting, Dribbling",
							personality: "Joker",
							alias: "Kento",
							height: "182cm",
							strongFoot: "Right",
							emoji: "😜",
							joined: "2016",
							games: 35,
							goals: 15,
							assists: 5,
							favouriteMove: "The Chop",
							playerTake:
								"Dabonii is family. Here you feel right at home and the togetherness elevates you to a different level.",
						},
						{
							name: "Pepe",
							age: "35",
							position: "Attacking Midfielder",
							id: 2,
							strengths: "Passing, shooting, Dribbling",
							personality: "Competent",
							alias: "Pepe",
							height: "179cm",
							strongFoot: "Right",
							emoji: "🙂",
							joined: "2016",
							games: 30,
							goals: 13,
							assists: 7,
							favouriteMove: "The Long Pass",
							playerTake:
								"Dabonii is family. Here you feel right at home and the togetherness elevates you to a different level.",
						},

						{
							name: "Eliud",
							age: "30",
							position: "Attacking Midfielder",
							id: 3,
							strengths: "Vision, Passing, Dribbling",
							personality: "Compassionate",
							alias: "Elude",
							height: "175cm",
							strongFoot: "Right",
							emoji: "☺️",
							joined: "2016",
							games: 32,
							goals: 10,
							assists: 8,
							favouriteMove: "The Fake Shot",
							playerTake:
								"Dabonii is family. Here you feel right at home and the togetherness elevates you to a different level.",
						},

						{
							name: "Cecil",
							age: "24",
							position: "Attacking Midfielder",
							id: 4,
							strengths: "Speed, Passing, Dribbling",
							personality: "Outgoing",
							alias: "Cecil",
							height: "176cm",
							strongFoot: "Right",
							emoji: "😜",
							joined: "2024",
							games: 0,
							goals: 0,
							assists: 0,
							favouriteMove: "Footwork",
							playerTake:
								"Dabonii is family. Here you feel right at home and the togetherness elevates you to a different level.",
						},

						{
							name: "Eric Muiruri",
							age: "23",
							position: "Attacking Midfielder",
							id: 5,
							strengths: "Shooting, Dribbling, Passing",
							personality: "Competent",
							alias: "Erico",
							height: "175cm",
							strongFoot: "Right",
							emoji: "😁",
							joined: "2016",
							games: 15,
							goals: 5,
							assists: 3,
							favouriteMove: "The Forward Touch",
							playerTake:
								"Dabonii is family. Here you feel right at home and the togetherness elevates you to a different level.",
						},
						{
							name: "Austin",
							age: "40",
							position: "Attacking Midfielder",
							id: 6,
							strengths: "Shooting, Dribbling",
							personality: "Competent",
							alias: "Sumba",
							height: "176cm",
							strongFoot: "Right",
							emoji: "😇",
							joined: "2016",
							games: 15,
							goals: 2,
							assists: 1,
							favouriteMove: "The Close Dribble",
							playerTake:
								"Dabonii is family. Here you feel right at home and the togetherness elevates you to a different level.",
						},
					],
				},
				{
					DefensiveMidfielders: [
						{
							name: "Ojalo",
							age: "24",
							position: "Defensive Midfielder",
							id: 1,
							strengths: "Tackling, Passing",
							personality: "Humble",
							alias: "Ojalo",
							height: "178cm",
							strongFoot: "Right",
							emoji: "😊",
							joined: "2024",
							games: 7,
							goals: 1,
							assists: 0,
							favouriteMove: "The one-two",
							playerTake:
								"Dabonii is family. Here you feel right at home and the togetherness elevates you to a different level.",
						},
						{
							name: "Constant Mulah",
							age: "34",
							position: "Defensive Midfielder",
							id: 2,
							strengths: "Tough, Stamina",
							personality: "Tenacious",
							alias: "Collo",
							height: "171cm",
							strongFoot: "Right",
							emoji: "😌",
							joined: "2016",
							games: 30,
							goals: 4,
							assists: 3,
							favouriteMove: "The Long Switch",
							playerTake:
								"Dabonii is family. Here you feel right at home and the togetherness elevates you to a different level.",
						},
						{
							name: "Kibe",
							age: "32",
							position: "Defensive Midfielder",
							id: 3,
							strengths: "Stamina, Shooting, Dribbling",
							personality: "Courageous",
							alias: "Kibe",
							height: "183cm",
							strongFoot: "Right",
							emoji: "😊",
							joined: "2024",
							games: 15,
							goals: 3,
							assists: 4,
							favouriteMove: "The Quick Dart",
							playerTake:
								"Dabonii is family. Here you feel right at home and the togetherness elevates you to a different level.",
						},
						{
							name: "Castro Opiyo",
							age: "33",
							position: "Defensive Midfielder",
							id: 4,
							strengths: "Passing, Vision, Strength",
							personality: "Compassionate",
							alias: "Castro",
							height: "184cm",
							strongFoot: "Right",
							emoji: "😊",
							joined: "2024",
							games: 18,
							goals: 0,
							assists: 2,
							favouriteMove: "The Long Pass",
							playerTake:
								"Dabonii is family. Here you feel right at home and the togetherness elevates you to a different level.",
						},
					],
				},
			],
		},
		{
			attackers: [
				{
					strikers: [
						{
							name: "Walter Masinde",
							age: "42",
							position: "Striker",
							id: 1,
							strengths: "Eye-for-goal, Strength, Finishing",
							personality: "Easy-going",
							alias: "Simba",
							height: "174cm",
							strongFoot: "Right",
							emoji: "😊",
							joined: "2016",
							games: 30,
							goals: 9,
							assists: 6,
							favouriteMove: "Muongeze",
							playerTake:
								"Dabonii is family. Here you feel right at home and the togetherness elevates you to a different level.",
						},
						{
							name: "Mzee Bonnie",
							age: "58",
							position: "Striker",
							id: 2,
							strengths: "First Touch, Dribbling, Passing",
							personality: "Compassion",
							alias: "Mzae",
							height: "175cm",
							strongFoot: "Right",
							emoji: "😊",
							joined: "2020",
							games: 20,
							goals: 5,
							assists: 3,
							favouriteMove: "The Close Dribble",
							playerTake:
								"Dabonii is family. Here you feel right at home and the togetherness elevates you to a different level.",
						},
						{
							name: "Tom Muriuki",
							age: "36",
							position: "Striker",
							id: 3,
							strengths: "Very Agile, Eye-for-goal",
							personality: "Friendly",
							alias: "Castro",
							height: "184cm",
							strongFoot: "Right",
							emoji: "😊",
							joined: "2024",
							games: 18,
							goals: 0,
							assists: 2,
							favouriteMove: "The Long Pass",
							playerTake:
								"Dabonii is family. Here you feel right at home and the togetherness elevates you to a different level.",
						},

						{
							name: "Eliud Oboya",
							age: "32",
							position: "Striker",
							id: 5,
							strengths: "Dribbling, Passing, Strength",
							personality: "Outgoing",
							alias: "Castro",
							height: "184cm",
							strongFoot: "Right",
							emoji: "😊",
							joined: "2024",
							games: 18,
							goals: 0,
							assists: 2,
							favouriteMove: "The Long Pass",
							playerTake:
								"Dabonii is family. Here you feel right at home and the togetherness elevates you to a different level.",
						},
					],
				},
				{
					wingers: [
						{
							name: "Anderson Ajore",
							age: "40",
							position: "Right Winger",
							id: 4,
							strengths: "Shooting, Dribbling",
							personality: "Competent",
							alias: "Castro",
							height: "184cm",
							strongFoot: "Right",
							emoji: "😊",
							joined: "2024",
							games: 18,
							goals: 0,
							assists: 2,
							favouriteMove: "The Long Pass",
							playerTake:
								"Dabonii is family. Here you feel right at home and the togetherness elevates you to a different level.",
						},
						{
							name: "Brian Nyamairi",
							age: "23",
							position: "Left Winger",
							id: 6,
							strengths: "Speed, Positioning",
							personality: "Competent",
							alias: "Castro",
							height: "184cm",
							strongFoot: "Right",
							emoji: "😊",
							joined: "2024",
							games: 18,
							goals: 0,
							assists: 2,
							favouriteMove: "The Long Pass",
							playerTake:
								"Dabonii is family. Here you feel right at home and the togetherness elevates you to a different level.",
						},
						{
							name: "Bubbah",
							age: "24",
							position: "Left Winger",
							id: 7,
							strengths: "Dribbling, Passing",
							personality: "Brave",
							alias: "Castro",
							height: "184cm",
							strongFoot: "Right",
							emoji: "😊",
							joined: "2024",
							games: 18,
							goals: 0,
							assists: 2,
							favouriteMove: "The Long Pass",
							playerTake:
								"Dabonii is family. Here you feel right at home and the togetherness elevates you to a different level.",
						},
						{
							name: "Kip Argut",
							age: "26",
							position: "Right Winger",
							id: 8,
							strengths: "Speed, Dribbling",
							personality: "Friendly",
							alias: "Castro",
							height: "184cm",
							strongFoot: "Right",
							emoji: "😊",
							joined: "2024",
							games: 18,
							goals: 0,
							assists: 2,
							favouriteMove: "The Long Pass",
							playerTake:
								"Dabonii is family. Here you feel right at home and the togetherness elevates you to a different level.",
						},
						{
							name: "Olise",
							age: "23",
							position: "Right Winger",
							id: 9,
							strengths: "Shooting, Dribbling, First-Touch",
							personality: "Competent",
							alias: "Castro",
							height: "184cm",
							strongFoot: "Right",
							emoji: "😊",
							joined: "2024",
							games: 18,
							goals: 0,
							assists: 2,
							favouriteMove: "The Long Pass",
							playerTake:
								"Dabonii is family. Here you feel right at home and the togetherness elevates you to a different level.",
						},
						{
							name: "Brayo Lefty",
							age: "25",
							position: "Right Winger",
							id: 10,
							strengths: "Shooting, Dribbling, Tackling",
							personality: "Brave",
							alias: "Castro",
							height: "184cm",
							strongFoot: "Right",
							emoji: "😊",
							joined: "2024",
							games: 18,
							goals: 0,
							assists: 2,
							favouriteMove: "The Long Pass",
							playerTake:
								"Dabonii is family. Here you feel right at home and the togetherness elevates you to a different level.",
						},
						{
							name: "Peter",
							age: "35",
							position: "Left Winger",
							id: 11,
							strengths: "Pace, Stamina, Finishing",
							personality: "Courageous",
							alias: "Sir Willy",
							height: "184cm",
							strongFoot: "Right",
							emoji: "😊",
							joined: "2024",
							games: 18,
							goals: 0,
							assists: 2,
							favouriteMove: "The Long Pass",
							playerTake:
								"Dabonii is family. Here you feel right at home and the togetherness elevates you to a different level.",
						},
						{
							name: "Denis Olomire",
							age: "32",
							position: "Left Winger",
							id: 12,
							strengths: "Stamina, tenacious",
							personality: "Courageous",
							alias: "Olomire",
							height: "169cm",
							strongFoot: "Left",
							emoji: "😬",
							joined: "2024",
							games: 10,
							goals: 0,
							assists: 0,
							favouriteMove: "The Laces Shot",
							playerTake:
								"Dabonii is family. Here you feel right at home and the togetherness elevates you to a different level.",
						},
					],
				},
			],
		},
	];
};

/**Get All Data */
export const getOffice = () => {
	return [
		{
			id: 1,
			name: "Kevin Sialenga",
			position: "Chairman",
			photo: "photo-chair",
		},
		{
			id: 2,

			name: "Boniface Ngwili",
			position: "Patron",
			photo: "patron-photo",
		},
		{
			id: 3,

			name: "Robert Sifuma",
			position: "Vice Chairman",
			photo: "photo-vice-chair",
		},
		{
			id: 4,

			name: "Tom Muriuki",
			position: "Treasurer",
			photo: "photo-treasurer",
			helper: [
				{
					id: 4.1,

					name: "Eshbon Ngotho",
					position: "Assistant Treasurer",
					photo: "photo-treasurer",
				},
			],
		},
		{
			id: 5,

			name: "Walter Masinde",
			position: "Organising Secretary",
			photo: "photo-organising-secretary",
			helper: [
				{
					id: 5.1,

					name: "Kennedy Atendo",
					position: "Assistant Organising Secretary",
					photo: "photo-asst-org-1",
				},
				{
					id: 5.2,

					name: "Anderson Ajore",
					position: "Assistant Organising Secretary",
					photo: "photo-asst-org-2",
				},
			],
		},
		{
			id: 6,

			name: "Brian Nyamairi",
			position: "Secretary",
			photo: "photo-secretary",
			helper: [
				{
					id: 6.1,

					name: "Dennis Andale",
					position: "Assistant Secretary",
					photo: "photo-secretary",
				},
			],
		},
		{
			id: 7,

			name: "Fredrick Mogaka",
			position: "Team Manager",
			photo: "photo-team-manager",
		},
		{
			honourableMembers: [
				{
					id: 8,

					name: "Samuel Njoroge",
					position: "Member",
					photo: "photo-member-1",
				},
				{
					id: 9,

					name: "Eric Karin",
					position: "Member",
					photo: "photo-member-2",
				},
				{
					id: 10,

					name: "Kevin Wambugu",
					position: "Member",
					photo: "photo-member-3",
				},
				{
					id: 11,

					name: "Joseph Ngina",
					position: "Member",
					photo: "photo-member-4",
				},
				{
					id: 12,

					name: "Martin Mbaya",
					position: "Member",
					photo: "photo-member-5",
				},
			],
		},
	];
};

/**DEFENDERS DATA */
export const getCenterBacks = () => {
	return [
		{
			name: "Samuel Njoroge",
			age: 37,
			position: "CB",
			id: 1,
			strengths: "Stamina, Positioning",
			personality: "Competent",
		},
		{
			name: "Elijah Owino",
			age: 29,
			position: "CB",
			id: 2,
			strengths: "Passing, First-Touch",
			personality: "Brave",
		},
		{
			name: "Eutychus",
			age: 20,
			position: "CB",
			id: 3,
			strengths: "Stamina, Pace",
			personality: "Competent",
		},
		{
			name: "Alex Mwangi",
			age: 34,
			position: "CB",
			id: 4,
			strengths: "Tackling,Strength",
			personality: "Brave",
		},
		{
			name: "Joseph Ngina",
			age: 39,
			position: "CB",
			id: 5,
			strengths: "Hard-Tackler, Passing",
			personality: "Honest",
		},
		{
			name: "Lwanga Viketi",
			age: 43,
			position: "CB",
			id: 6,
			strengths: "Tackling, Stamina",
			personality: "Competent",
		},
		{
			name: "Robert Sifuma",
			age: 40,
			position: "CB",
			id: 7,
			strengths: "Shooting,",
			personality: "Joker",
		},
		{
			name: "Idris",
			age: 31,
			position: "CB",
			id: 8,
			strengths: "Stamina, Pace, Power",
			personality: "Competent",
		},
	];
};

export const getFullbacks = () => {
	return [
		{
			name: "Joshua Junior",
			age: "28",
			position: "RB",
			id: 1,
			strengths: "Stamina, Pace",
			personality: "Competent",
		},
		{
			name: "Omanyala Oma",
			age: "23",
			position: "RB",
			id: 2,
			strengths: "Tackling, Speed",
			personality: "Brave",
		},
		{
			name: "Eshbon Moha",
			age: "35",
			position: "LB",
			id: 3,
			strengths: "Touch, Short Passes",
			personality: "Outgoing",
		},
		{
			name: "Martin Mbaya",
			age: "38",
			position: "RB",
			id: 4,
			strengths: "Dribbling, Long Passes",
			personality: "Humble",
		},
		{
			name: "Dan Lumiti",
			age: "31",
			position: "RB",
			id: 5,
			strengths: "Stamina, Pace",
			personality: "Brave",
		},
		{
			name: "Chris Jadolo",
			age: "40",
			position: "RB",
			id: 6,
			strengths: "Positioning, Man-marking",
			personality: "Compassionate",
		},
		{
			name: "Clinton Bukele",
			age: "26",
			position: "LB",
			id: 7,
			strengths: "Tackling, Passing",
			personality: "Competent",
		},
		{
			name: "Mugesto",
			age: "25",
			position: "RB",
			id: 8,
			strengths: "Passing, Vision",
			personality: "Brave",
		},
		{
			name: "Kasee",
			age: "36",
			position: "RB",
			id: 9,
			strengths: "Stamina, Pace",
			personality: "Competent",
		},
		{
			name: "Rutto",
			age: "42",
			position: "RB",
			id: 10,
			strengths: "Tenacious, Tackling",
			personality: "Brave",
		},
	];
};

// export const getGoalkeepers = () => {
// 	return [
// 		{
// 			name: "Allan Allano",
// 			age: 31,
// 			position: "Goalkeeper",
// 			id: 1,
// 			strengths: "Sweeping, Long Passes, Cross-Claiming",
// 			personality: "Courageous",
// 		},
// 		{
// 			name: "Collins Collo",
// 			age: 17,
// 			position: "Goalkeeper",
// 			id: 2,
// 			strengths: "Cross-Claiming, Sweeper",
// 			personality: "Courageous",
// 		},
// 		{
// 			name: "Jagoal",
// 			age: 23,
// 			position: "Goalkeeper",
// 			id: 3,
// 			strengths: "Shot-Stopper",
// 			personality: "Humble",
// 		},
// 	];
// };

/**MIDFIELERS DATA */

export const getMidfielders = () => {
	return [
		{
			name: "Kennedy Atendo",
			age: "31",
			position: "Attacking Midfielder",
			id: 1,
			strengths: "speed, shooting, Dribbling",
			personality: "joker",
		},
		{
			name: "Pepe",
			age: "35",
			position: "Attacking Midfielder",
			id: 2,
			strengths: "Passing, shooting, Dribbling",
			personality: "Competent",
		},
		{
			name: "Constant Mulah",
			age: "34",
			position: "Defensive Midfielder",
			id: 3,
			strengths: "Tough, Stamina",
			personality: "Tenacious",
		},
		{
			name: "Eliud",
			age: "30",
			position: "Attacking Midfielder",
			id: 4,
			strengths: "Vision, Passing, Dribbling",
			personality: "Compassionate",
		},
		{
			name: "Ojalo",
			age: "24",
			position: "Defensive Midfielder",
			id: 5,
			strengths: "Tackling, Passing",
			personality: "Humble",
		},
		{
			name: "Cecil",
			age: "24",
			position: "Attacking Midfielder",
			id: 6,
			strengths: "Speed, Passing, Dribbling",
			personality: "Outgoing",
		},
		{
			name: "Kibe",
			age: "32",
			position: "Defensive Midfielder",
			id: 7,
			strengths: "Stamina, Shooting, Dribbling",
			personality: "Courageous",
		},
		{
			name: "Eric Muiruri",
			age: "23",
			position: "Attacking Midfielder",
			id: 8,
			strengths: "Shooting, Dribbling, Passing",
			personality: "Competent",
		},
		{
			name: "Castro Opiyo",
			age: "33",
			position: "Defensive Midfielder",
			id: 9,
			strengths: "Passing, Vision, Strength",
			personality: "Compassionate",
		},
	];
};

/** ATTACKERS DATA */

export const getAttackers = () => {
	return [
		{
			name: "Walter Masinde",
			age: "42",
			position: "Striker",
			id: 1,
			strengths: "Eye-for-goal, Strength, Finishing",
			personality: "Easy-going",
		},
		{
			name: "Mzee Bonnie",
			age: "58",
			position: "Striker",
			id: 2,
			strengths: "First Touch, Dribbling, Passing",
			personality: "Compassion",
		},
		{
			name: "Tom Muriuki",
			age: "36",
			position: "Striker",
			id: 3,
			strengths: "Very Agile, Eye-for-goal",
			personality: "Friendly",
		},
		{
			name: "Anderson Ajore",
			age: "40",
			position: "Right Winger",
			id: 4,
			strengths: "Shooting, Dribbling",
			personality: "Competent",
		},
		{
			name: "Eliud Oboya",
			age: "32",
			position: "Striker",
			id: 5,
			strengths: "Dribbling, Passing, Strength",
			personality: "Outgoing",
		},
		{
			name: "Brian Nyamairi",
			age: "23",
			position: "Left Winger",
			id: 6,
			strengths: "Speed, Positioning",
			personality: "Competent",
		},
		{
			name: "Bubbah",
			age: "24",
			position: "Left Winger",
			id: 7,
			strengths: "Dribbling, Passing",
			personality: "Brave",
		},
		{
			name: "Kip Argut",
			age: "26",
			position: "Right Winger",
			id: 8,
			strengths: "Speed, Dribbling",
			personality: "Friendly",
		},
		{
			name: "Olise",
			age: "23",
			position: "Right Winger",
			id: 9,
			strengths: "Shooting, Dribbling, First-Touch",
			personality: "Competent",
		},
		{
			name: "Brayo Lefty",
			age: "25",
			position: "Right Winger",
			id: 10,
			strengths: "Shooting, Dribbling, Tackling",
			personality: "Brave",
		},
		{
			name: "Peter",
			age: "35",
			position: "Left Winger",
			id: 11,
			strengths: "Pace, Stamina, Finishing",
			personality: "Courageous",
		},
	];
};
